//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Imagenes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Imagenes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentacion.Imagenes", typeof(Imagenes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Add_Files_To_Archive_32 {
            get {
                object obj = ResourceManager.GetObject("Add-Files-To-Archive-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add_Files_To_Archive_64 {
            get {
                object obj = ResourceManager.GetObject("Add-Files-To-Archive-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Buscar2 {
            get {
                object obj = ResourceManager.GetObject("Buscar2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Buscar2_32 {
            get {
                object obj = ResourceManager.GetObject("Buscar2_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap carrito {
            get {
                object obj = ResourceManager.GetObject("carrito", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap carrito1 {
            get {
                object obj = ResourceManager.GetObject("carrito1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap comercio_online {
            get {
                object obj = ResourceManager.GetObject("comercio_online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap devolucion {
            get {
                object obj = ResourceManager.GetObject("devolucion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap devolucion1 {
            get {
                object obj = ResourceManager.GetObject("devolucion1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap devolucion1_32 {
            get {
                object obj = ResourceManager.GetObject("devolucion1_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap devolucion2 {
            get {
                object obj = ResourceManager.GetObject("devolucion2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dialog_Apply_24 {
            get {
                object obj = ResourceManager.GetObject("Dialog-Apply-24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dialog_Apply_64 {
            get {
                object obj = ResourceManager.GetObject("Dialog-Apply-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Emblem_Money_64 {
            get {
                object obj = ResourceManager.GetObject("Emblem-Money-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap equipo {
            get {
                object obj = ResourceManager.GetObject("equipo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Accessories_Text_Editor_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Accessories-Text-Editor-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Address_Book_New_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Address-Book-New-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Applications_Other_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Applications-Other-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Applications_Utilities_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Applications-Utilities-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Bookmark_New_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Bookmark-New-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Camera_Video_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Camera-Video-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Dialog_Question_24 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Dialog-Question-24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Document_New_48 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Document-New-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Document_New_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Document-New-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Document_Save_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Document-Save-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Document_Save_641 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Document-Save-641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Edit_Clear_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Edit-Clear-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Edit_Redo_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Edit-Redo-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Edit_Redo_64__2_ {
            get {
                object obj = ResourceManager.GetObject("Gnome-Edit-Redo-64 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Emblem_Shared_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Emblem-Shared-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Emblem_Symbolic_Link_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Emblem-Symbolic-Link-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Face_Cool_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Face-Cool-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Media_Seek_Backward_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Media-Seek-Backward-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Media_Seek_Forward_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Media-Seek-Forward-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Media_Skip_Backward_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Media-Skip-Backward-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Media_Skip_Forward_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Media-Skip-Forward-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Media_Zip_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Media-Zip-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Network_Transmit_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Network-Transmit-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_save_Zip_32 {
            get {
                object obj = ResourceManager.GetObject("Gnome-save-Zip-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_System_Log_Out_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-System-Log-Out-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_System_Log_Out_641 {
            get {
                object obj = ResourceManager.GetObject("Gnome-System-Log-Out-641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_System_Run_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-System-Run-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_System_Search_32 {
            get {
                object obj = ResourceManager.GetObject("Gnome-System-Search-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Undelete_24 {
            get {
                object obj = ResourceManager.GetObject("Gnome-Undelete-24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_User_Desktop_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-User-Desktop-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_View_Sort_Descending_64 {
            get {
                object obj = ResourceManager.GetObject("Gnome-View-Sort-Descending-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gold_Theme_Money_Dollars_clip_art_hight {
            get {
                object obj = ResourceManager.GetObject("Gold_Theme_Money_Dollars_clip_art_hight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gold_Theme_Money_Dollars_clip_art_hight1 {
            get {
                object obj = ResourceManager.GetObject("Gold_Theme_Money_Dollars_clip_art_hight1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icono_dinero {
            get {
                object obj = ResourceManager.GetObject("icono_dinero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lector {
            get {
                object obj = ResourceManager.GetObject("lector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lectores {
            get {
                object obj = ResourceManager.GetObject("lectores", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lectores_principal {
            get {
                object obj = ResourceManager.GetObject("lectores_principal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prestamo {
            get {
                object obj = ResourceManager.GetObject("prestamo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sell {
            get {
                object obj = ResourceManager.GetObject("sell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User_Info_64 {
            get {
                object obj = ResourceManager.GetObject("User-Info-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
